name: CI/CD for phone-registrations

on:
  push:
    branches:
      - development


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
